<!DOCTYPE HTML PUBLIC  "-//W3C//DTD HTML 4.01 Transitional//EN"  "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>建设部门通讯录 - {$title}</title>
        <link type="text/css" rel="stylesheet" href="{$voc_root}/css/base_1.0.css"/>
        <link type="text/css" rel="stylesheet" href="{$voc_root}/css/tool_1.0.css"/>
        <link rel="shortcut icon" href="{$voc_root}/imgs/system/favicon.ico"/>
        <!--[if IE 6]>
            <link type="text/css" rel="stylesheet" href="{$voc_root}/css/ie6_1.0.css"/>
        <![endif]-->
        <script type="text/javascript" src="{$voc_root}/config/loader.js" id="loader">5</script>
        <meta name='keywords' content='{$kwds}'>
        <meta name='description' content='{$desc}'>
    </head>
    <body>
        <if condition="$login eq 1">
        <!-- layout::{$bheader}::0 -->
        <else/>
        <div class="bdheader" id="bdheader">
            <!-- layout::Public:n_header::0 -->
        </div>
        </if>
        <div class="layout1 conbook">
            <div class="t_title">
                <p class="name">建设部门通讯录</p>
                <p class="liner"></p>
            </div>
            <div class="sort_in toolnav">
                <a class="blue fa sel" href="#jz_book" rel="jz_book" title="建造师执业资格">1. 建造师执业资格</a>
                <a class="blue fb" href="#zj_book" rel="zj_book"  title="造价师执业资格">2. 造价师执业资格</a>
                <a class="blue fc" href="#jl_book" rel="jl_book"  title="监理师执业资格">3. 监理师执业资格</a>
                <a class="blue fd" href="#kc_book" rel="kc_book"  title="勘察设计执业资格">4. 勘察设计执业资格</a>
            </div>
            <div id="jz_book"class="bc first">
                <p class="gn">建造师执业资格注册管理机构通讯录</p>
                <table class="tb_c ta">
                    <tr>
                        <td class="gray procv">
                            省（市）
                        </td>
                        <td class="gray orgination">
                            注册管理机构
                        </td>
                        <td class="gray phnuber">
                            联系电话
                        </td>
                         <td class=" gray addr">
                            办理地址
                        </td>
                         <td class="gray material">
                            材料
                        </td>
                         <td class="gray prgs">
                            流程
                        </td>
                    </tr>
                    <tr>
                        <td>
                            全国
                        </td>
                        <td>
                            <a href="http://www.mohurd.gov.cn" class="blue" target="_blank">住房和城乡建设部</a>
                        </td>
                        <td>
                            010-88381873<br/>010-88381891
                        </td>
                        <td>
                            北京市海淀区三河里路9号
                        </td>
                        <td>
                           -
                        </td>
                        <td>
                           -
                        </td>
                    </tr>
                      <tr>
                        <td>
                            北京
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn" class="blue" target="_blank">北京市住房和城乡建设委员会</a>
                        </td>
                        <td>
                            010-59958555<br/>010-59958185
                        </td>
                        <td>
                            北京市海淀区西四环中路16号院3号楼
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn/publish/portal0/tab2277/" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn/publish/portal0/tab2276/" class="blue" target="_blank">流程</a>
                        </td>
                    </tr>
                      <tr>
                        <td>
                            天津
                        </td>
                        <td>
                            <a href="http://www.tjcac.gov.cn" class="blue" target="_blank">天津建委</a>
                        </td>
                        <td>
                            022-24538461
                        </td>
                        <td>
                            天津市和平区南京路131号城建大厦A座2004
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            上海
                        </td>
                        <td>
                            <a href="http://www.ciac.sh.cn" class="blue" target="_blank">上海建筑建材业网</a>
                        </td>
                        <td>
                            021-27129778
                        </td>
                        <td>
                            上海市徐汇区小木桥路683号受理大厅
                        </td>
                        <td>
                            <a href="http://www.ciac.sh.cn/zxfw_new_ry.aspx" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            重庆
                        </td>
                        <td>
                            <a href="http://www.ccc.gov.cn" class="blue" target="_blank">重庆市建筑管理总站</a>
                        </td>
                        <td>
                            023-63672121
                        </td>
                        <td>
                            渝中区长江一路58号市城乡建委政务服务中心4楼11号窗口
                        </td>
                        <td>
                            <a href="http://www.tjcac.gov.cn/jzy/detail.asp?articleid=14773&classid=343" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河北
                        </td>
                        <td>
                            <a href="http://www.hebjs.gov.cn " class="blue" target="_blank">河北省住房和城乡建设厅执业资格注册中心</a>
                        </td>
                        <td>
                            0311-87908200<br/>0311-87800670
                        </td>
                        <td>
                            河北省住房和城乡建设厅行政审批大厅（石家庄市新华路501号）
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山西
                        </td>
                        <td>
                            <a href="http://www.sxjs.gov.cn" class="blue" target="_blank">山西省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0351-3581377
                        </td>
                        <td>
                            山西省太原市建设北路85号山西省住房和城乡建设厅政务大厅
                        </td>
                        <td>
                            <a href="http://www.sxjs.gov.cn/NewsRead.aspx?CatalogId=142&refId=17316" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            内蒙古
                        </td>
                        <td>
                            <a href="http://www.nmgjsw.gov.cn" class="blue" target="_blank">内蒙古住房和城乡建设厅</a>
                        </td>
                        <td>
                            023-63672121
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.nmgjsw.gov.cn/information/nmjs1/msg19995475.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            黑龙江
                        </td>
                        <td>
                            <a href="http://www.hljjs.gov.cn" class="blue" target="_blank">黑龙江建设厅</a>
                        </td>
                        <td>
                            0421-53644878
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            吉林
                        </td>
                        <td>
                            <a href="http://jst.jl.gov.cn" class="blue" target="_blank">吉林省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0431-82752560(562)
                        </td>
                        <td>
                            吉林省长春市贵阳街287号建设大厦27楼2701房间
                        </td>
                        <td>
                            <a href="http://jst.jl.gov.cn/zwgk/xmsp/200809/t20080919_446148.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            辽宁
                        </td>
                        <td>
                            <a href="http://www.zczx.lnjst.gov.cn" class="blue" target="_blank">辽宁省住房和城乡建设执业资格注册中心</a>
                        </td>
                        <td>
                            02423974459<br/>02423975869
                        </td>
                        <td>
                            辽宁省沈阳市和平区三好街93号
                        </td>
                        <td>
                            <a href="http://www.zczx.lnjst.gov.cn/(S(ajl42n55mifzpi45q2kilt45))/zyzc/childzhu.aspx" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江苏
                        </td>
                        <td>
                            <a href="http://www.jscin.gov.cn" class="blue" target="_blank">江苏省住房和城乡建设厅</a>
                        </td>
                        <td>
                            025-51868921
                        </td>
                        <td>
                            江苏建设大厦2楼(南京市鼓楼区草场门大街88号)
                        </td>
                        <td>
                            <a href="http://zw.jscin.gov.cn:88/lescms/websites/zw.jscin.gov.cn/bszn.jsp?LESXMLROWSETGOTOPAGENUMBER=1" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山东
                        </td>
                        <td>
                            <a href="http://www.sdjs.gov.cn" class="blue" target="_blank">山东省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0531-87087200<br/>0531-87087263<br/>0531-87087271
                        </td>
                        <td>
                            山东省济南市市中区经五小纬四路46号 
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            安徽
                        </td>
                        <td>
                            <a href="http://www.ahjst.gov.cn" class="blue" target="_blank">安徽省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0551-2999765
                        </td>
                        <td>
                            合肥市马鞍山路509号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            浙江
                        </td>
                        <td>
                            <a href="http://www.zjjs.com.cn" class="blue" target="_blank">浙江省建设信息港</a>
                        </td>
                        <td>
                            0571-85213535
                        </td>
                        <td>
                            浙江省杭州市省府路8号省府大楼2号楼 
                        </td>
                        <td>
                            <a  target="_blank"href="http://www.zjjs.com.cn/DesktopModules/Winstar2004.JstZz.ExecutiveAllow/DetailInfoShow.aspx?ItemID=d0b5c8d2-e888-4c80-ad5b-153ed8cbfc60" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            福建
                        </td>
                        <td>
                            <a href="http://www.fjjs.gov.cn" class="blue" target="_blank">福建省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0591－87617396
                        </td>
                        <td>
                            福州市北大路242号建设公寓一楼政务中心
                        </td>
                        <td>
                            <a href="http://www.fjjs.gov.cn/Htgl/Dhym/Wsbs/baznshow.aspx?FileName=bszn,sp_jzhs" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江西
                        </td>
                        <td>
                            <a href="http://www.jxjst.gov.cn" class="blue" target="_blank">江西省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0791-86270103<br/>0791-86286121<br/>0791-86237297
                        </td>
                        <td>
                            江西省南昌市省政府大院内北二路119号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河南
                        </td>
                        <td>
                            <a href="http://www.hnjs.gov.cn" class="blue" target="_blank">河南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0371－68080730<br/>0371－69523923
                        </td>
                        <td>
                            郑州市郑东新区商务内环路29号新蒲大厦14楼1406房间
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖北
                        </td>
                        <td>
                            <a href="http://www.hbzfhcxjst.gov.cn" class="blue" target="_blank">湖北省住房和城乡建设厅</a>
                        </td>
                        <td>
                            027-68873377<br/>027-68873332
                        </td>
                        <td>
                            武昌中南路12号建设大厦A座12楼1207室 每周一、周二受理材料
                        </td>
                        <td>
                            <a  target="_blank" href="http://www.hbzfhcxjst.gov.cn/Web/Article/2009/06/24/1151221792.aspx?ArticleID=001ce0d5-d2fe-49ae-8a98-3b7d6adc22c1" class="blue">材料</a>
                        </td>
                        <td>
                            <a href="http://www.hbzfhcxjst.gov.cn/UpFiles/xzxk/lct/jzs.htm" class="blue">流程</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖南
                        </td>
                        <td>
                            <a href="http://www.hunanjs.gov.cn" class="blue" target="_blank">湖南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0731-88950141<br/>0731-88950140
                        </td>
                        <td>
                            长沙市洞井街道和平社区
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广东
                        </td>
                        <td>
                            <a href="http://www.gdzczx.com" class="blue" target="_blank">广东省建设执业资格注册中心</a>
                        </td>
                        <td>
                            020-86375268<br/>020-86373218<br/>020-83754271
                        </td>
                        <td>
                            广东省广州市越秀区华乐路53号华乐大厦南塔14楼
                        </td>
                        <td>
                            <a href="http://www.gdzczx.com/gdzczxIms/zcdt/" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广西
                        </td>
                        <td>
                            <a href="http://www.gxcic.net" class="blue" target="_blank">广西建设厅</a>
                        </td>
                        <td>
                            0771-5595842
                        </td>
                        <td>
                            广西南宁市怡宾路6号
                        </td>
                        <td>
                            <a href="http://www.gxcic.net/twgk/Show.aspx?id=93114" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            海南
                        </td>
                        <td>
                            <a href="http://www.hncic.net" class="blue" target="_blank">海南省住房和城乡建设厅建筑管理处</a>
                        </td>
                        <td>
                             0898-66231332<br/>0898-65342504
                        </td>
                        <td>
                            海口市海府路59号厅办公楼三楼316室
                        </td>
                        <td>
                            <a href="http://www.hizw.gov.cn/hiSP/html/WorkFlow/?1457_1" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            云南
                        </td>
                        <td>
                            <a href="http://www.ynjst.gov.cn" class="blue" target="_blank">云南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0871-4163856
                        </td>
                        <td>
                            云南省昆明市滇池路红塔路口昆明二建大厦三楼云南注册建造师管理办公室
                        </td>
                        <td>
                            <a href="http://www.ynjst-jgc.com/skynet/jgcweb/TypeInfo.aspx?id=2127" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            贵州
                        </td>
                        <td>
                            <a href="http://www.gzjs.gov.cn" class="blue" target="_blank">贵州省住房和城乡建设厅</a>
                        </td>
                        <td>
                             0851-5360015<br/>0851-5360288
                        </td>
                        <td>
                            延安西路２号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            四川
                        </td>
                        <td>
                            <a href="http://web.scjst.gov.cn" class="blue" target="_blank">四川省住房和城乡建设厅</a>
                        </td>
                        <td>
                            028-85453202<br/>028-85433567
                        </td>
                        <td>
                            四川省成都市武侯区致民路21号4楼人才服务大厅
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            西藏
                        </td>
                        <td>
                            <a href="http://www.xzcs.gov.cn" class="blue" target="_blank">西藏自治区建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            陕西
                        </td>
                        <td>
                            <a href="http://www.shaanxijs.gov.cn" class="blue" target="_blank">陕西省建设厅</a>
                        </td>
                        <td>
                            029-87283010<br/>029-87292026
                        </td>
                        <td>
                            陕西省西安市新城广场省政府大楼9楼66号建设厅建筑管理处
                        </td>
                        <td>
                            <a href="http://www.sjzz.org.cn/zhiye/722.shtml" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            甘肃
                        </td>
                        <td>
                            <a href="http://www.gsjs.com.cn" class="blue" target="_blank">甘肃省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            宁夏
                        </td>
                        <td>
                            <a href="http://www.nxzczx.com/SiteAcl.srv?id=2288188&publicstr=str"  target="_blank" class="blue">宁夏回族自治区住房和城乡建设厅</a>
                        </td>
                        <td>
                            0951-5099008<br/>0951-5011154
                        </td>
                        <td>
                            银川市兴庆区上海东路48号(建设大厦八楼注册科)
                        </td>
                        <td>
                            <a href="http://www.nxzczx.com/SiteAcl.srv?id=2288286&aid=2010003221&channelid=2288208" target="_blank"  class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            新疆
                        </td>
                        <td>
                            <a href="http://www.xjjs.gov.cn" class="blue" target="_blank">新疆建设厅</a>
                        </td>
                        <td>
                            0951-5179098<br/>0991-2830155
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.xjjs.gov.cn/main/NewsDetail.aspx?Id=38195" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            青海
                        </td>
                        <td>
                            <a href="http://www.qhcin.gov.cn" class="blue" target="_blank">青海省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0971-6146535<br/>0971-6108178
                        </td>
                        <td>
                            青海省西宁市五四大街四号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                </table>
            </div>
            <div id="zj_book" class="bc pt">
                 <p class="gn">造价师执业资格注册管理机构通讯录</p>
                   <table class="tb_c tb">
                    <tr>
                        <td class="gray procv">
                            省(市)
                        </td>
                        <td class="gray orgination">
                            注册管理机构
                        </td>
                        <td class="gray phnuber">
                            联系电话
                        </td>
                         <td class=" gray addr">
                            办理地址
                        </td>
                    </tr>
                    <tr>
                        <td>
                            北京
                        </td>
                        <td>
                            北京市住房和城乡建设委员会执业资格注册中心
                        </td>
                        <td>
                            010-59958992
                        </td>
                        <td>
                            北京市海淀区西四环中路16号院3号楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            天津
                        </td>
                        <td>
                            天津市建委行政许可中心
                        </td>
                        <td>
                            022-24538422
                        </td>
                        <td>
                            天津市河东区红星路79号2楼85#窗口
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河北
                        </td>
                        <td>
                            河北省建设厅执业资格注册中心
                        </td>
                        <td>
                            0311-87908201<br/>0311-87908204(F)
                        </td>
                        <td>
                            石家庄市新华路501号6213房间
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山西省
                        </td>
                        <td>
                            山西省建设厅行政审批中心
                        </td>
                        <td>
                            0351-3581160<br/>0351-3580137(F)
                        </td>
                        <td>
                            太原市建设北路85号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            内蒙古
                        </td>
                        <td>
                            内蒙古建设工程造价管理总站
                        </td>
                        <td>
                            0471-6917554<br/>0471-6913212(F)
                        </td>
                        <td>
                            呼和浩特市新华东街81号芳汀花园大厦十楼743号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            辽宁
                        </td>
                        <td>
                            辽宁省建设厅执业资格注册中心
                        </td>
                        <td>
                            024-23974410<br/>024-23974030
                        </td>
                        <td>
                            沈阳市和平区三好街93号金源大厦7楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            黑龙江
                        </td>
                        <td>
                            黑龙江省建设工程造价管理协会
                        </td>
                        <td>
                            0451-82303570<br/>0451-82352412(F)
                        </td>
                        <td>
                            哈尔滨市开发区昆仑商城康顺街1号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            吉林
                        </td>
                        <td>
                            吉林省建设工程造价管理站
                        </td>
                        <td>
                            0431-88922837
                        </td>
                        <td>
                            长春市同志街900号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            上海
                        </td>
                        <td>
                            上海市建筑建材业受理服务中心
                        </td>
                        <td>
                            021-54614788(5106)<br/>021-64437734(F)
                        </td>
                        <td>
                            上海市徐汇区小木桥路683号308室
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江苏
                        </td>
                        <td>
                            江苏省建设厅行政审批中心
                        </td>
                        <td>
                            025-51868919
                        </td>
                        <td>
                            南京市鼓楼区草场门88号2811房间
                        </td>
                    </tr>
                    <tr>
                        <td>
                            浙江
                        </td>
                        <td>
                            浙江省建设厅政务办理中心
                        </td>
                        <td>
                            0571-85213131
                        </td>
                        <td>
                            杭州市体育场路498号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            安徽
                        </td>
                        <td>
                            安徽省建设厅造价管理总站
                        </td>
                        <td>
                            0551-2880052
                        </td>
                        <td>
                            合肥市宣城路91号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            福建
                        </td>
                        <td>
                            福建省建设执业资格注册中心
                        </td>
                        <td>
                            0591-87546767<br/>0591-87617385(F)
                        </td>
                        <td>
                            福州市北大路242号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江西
                        </td>
                        <td>
                            江西省建设工程造价管理站
                        </td>
                        <td>
                            0791-8319060
                        </td>
                        <td>
                            南昌市北京东路1463号精英汇B栋507室
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山东
                        </td>
                        <td>
                            山东省建设厅执业资格注册中心
                        </td>
                        <td>
                            0531-87910142<br/>0531-87942024(F)
                        </td>
                        <td>
                            济南市经五路小纬四路46号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖北
                        </td>
                        <td>
                            湖北省建设工程造价管理总站
                        </td>
                        <td>
                            027-51826498<br/>027-51826499(F)
                        </td>
                        <td>
                            武汉武昌体育馆路2号新凯大厦十楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖南
                        </td>
                        <td>
                            湖南省建设工程定额管理站
                        </td>
                        <td>
                            0731-5588252
                        </td>
                        <td>
                            长沙市雨花亭桔园路125号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广东
                        </td>
                        <td>
                            广东省建设执业资格注册中心
                        </td>
                        <td>
                            020-83771003<br/>020-83754269(F)
                        </td>
                        <td>
                            广州市华乐路53号华乐大厦南塔14层
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广西
                        </td>
                        <td>
                            广西政务服务中心
                        </td>
                        <td>
                            0771-5595842/3<br/>0771-5595824(F)
                        </td>
                        <td>
                            南宁市怡宾路6号三楼建设厅窗口
                        </td>
                    </tr>
                    <tr>
                        <td>
                            海南
                        </td>
                        <td>
                            海南省建设培训与执业资格注册中心
                        </td>
                        <td>
                            0898-66219099<br/>0898-66219099(F)
                        </td>
                        <td>
                            海口市文联路6号金泰大酒店二楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            重庆
                        </td>
                        <td>
                            重庆市建设工程造价管理总站
                        </td>
                        <td>
                            023-63673008<br/>023-63671707(F)
                        </td>
                        <td>
                            重庆市渝中区长江一路58号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            四川
                        </td>
                        <td>
                            四川省建设工程造价管理总站
                        </td>
                        <td>
                            028-83352062<br/>028-83314911(F)
                        </td>
                        <td>
                            成都市星辉东路8号518室
                        </td>
                    </tr>
                    <tr>
                        <td>
                            贵州
                        </td>
                        <td>
                            贵州省建设厅政务中心
                        </td>
                        <td>
                            0851-5360016<br/>0851-5360015(F)
                        </td>
                        <td>
                            贵阳市延安西路2号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            云南
                        </td>
                        <td>
                            云南省住房和城乡建设厅标准定额处
                        </td>
                        <td>
                            0871-4320642<br/>0871-3636226(F)
                        </td>
                        <td>
                            云南省昆明市滇池路红塔东路
                        </td>
                    </tr>
                    <tr>
                        <td>
                            西藏
                        </td>
                        <td>
                            西藏建设厅政工人事教育处
                        </td>
                        <td>
                            0891-6833334
                        </td>
                        <td>
                            西藏区拉萨市娘热路13号
                        </td>
                    </tr>
                    <tr>
                        <td>
                            青海
                        </td>
                        <td>
                            青海省建设执业资格注册中心
                        </td>
                        <td>
                            0971-6146535
                        </td>
                        <td>
                            西宁市五四大街4号建筑科技书店3楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            陕西
                        </td>
                        <td>
                            陕西省建设厅执业资格注册中心
                        </td>
                        <td>
                            029-87283010<br/>029-87241792
                        </td>
                        <td>
                            西安市南新街28号德邻酒店311室
                        </td>
                    </tr>
                    <tr>
                        <td>
                            甘肃
                        </td>
                        <td>
                            甘肃省建设厅执业资格注册中心
                        </td>
                        <td>
                            0931-8470715<br/>0931-8470716(F)
                        </td>
                        <td>
                            兰州市静宁路305号建设大厦13楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            宁夏
                        </td>
                        <td>
                            宁夏建设工程造价管理站
                        </td>
                        <td>
                            0951-5058495
                        </td>
                        <td>
                            银川市解放西街103号卫生厅6楼
                        </td>
                    </tr>
                    <tr>
                        <td>
                            新疆
                        </td>
                        <td>
                            新疆建设厅标准定额处
                        </td>
                        <td>
                            0991-2823164
                        </td>
                        <td>
                            新疆乌鲁木齐市中山路462号广场联合办公楼13层
                        </td>
                    </tr>
                </table>
            </div>
            <div id="jl_book"class="bc pt">
                 <p class="gn">监理师执业资格注册管理机构通讯录</p>
                    <table class="tb_c tc">
                    <tr>
                        <td class="gray procv">
                            省(市)
                        </td>
                        <td class="gray orgination">
                            注册管理机构
                        </td>
                        <td class="gray phnuber">
                            联系电话
                        </td>
                         <td class=" gray addr">
                            办理地址
                        </td>
                         <td class="gray material">
                            材料
                        </td>
                         <td class="gray prgs">
                            流程
                        </td>
                    </tr>
                    <tr>
                        <td>
                            全国
                        </td>
                        <td>
                            <a href="http://www.zgjsjl.org.cn" class="blue">中国建设监理协会</a>
                        </td>
                        <td>
                            010-88385640<br/>010-88374175
                        </td>
                        <td>
                            北京市海淀区西四环北路158号慧科大厦10层
                        </td>
                        <td>
                           -
                        </td>
                        <td>
                           -
                        </td>
                    </tr>
                      <tr>
                        <td>
                            北京
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn" class="blue" target="_blank">北京市住房和城乡建设委员会</a>
                        </td>
                        <td>
                            010-59958555<br/>010-59958185
                        </td>
                        <td>
                            北京市海淀区西四环中路16号院3号楼
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn/publish/portal0/tab2277/" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn/publish/portal0/tab2276/" class="blue" target="_blank">流程</a>
                        </td>
                    </tr>
                      <tr>
                        <td>
                            天津
                        </td>
                        <td>
                            <a href="http://www.tjcac.gov.cn" class="blue" target="_blank">天津建委</a>
                        </td>
                        <td>
                            020-23301890
                        </td>
                        <td>
                            天津市和平区南京路131号城建大厦A座2004
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            上海
                        </td>
                        <td>
                            <a href="http://www.ciac.sh.cn" class="blue" target="_blank">上海建筑建材业网</a>
                        </td>
                        <td>
                            021-27129778
                        </td>
                        <td>
                            上海市徐汇区小木桥路683号受理大厅
                        </td>
                        <td>
                            <a href="http://www.ciac.sh.cn/zxfw_new_ry.aspx" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            重庆
                        </td>
                        <td>
                            <a href="http://www.ccc.gov.cn" class="blue" target="_blank">重庆市建委建筑管理处</a>
                        </td>
                        <td>
                            023-63672120
                        </td>
                        <td>
                            渝中区长江一路58号市城乡建委政务服务中心4楼11号窗口
                        </td>
                        <td>
                            <a href="http://www.tjcac.gov.cn/jzy/detail.asp?articleid=14773&classid=343" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河北
                        </td>
                        <td>
                            <a href="http://www.hebjs.gov.cn " class="blue" target="_blank">河北省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山西
                        </td>
                        <td>
                            <a href="http://www.sxjs.gov.cn" class="blue" target="_blank">山西省住房和城乡建设厅（山西监理协会）</a>
                        </td>
                        <td>
                            0351-3581190<br/>0351-2380132
                        </td>
                        <td>
                            山西省太原市建设北路85号山西省住房和城乡建设厅政务大厅
                        </td>
                        <td>
                            <a href="http://www.sxjs.gov.cn/NewsRead.aspx?CatalogId=142&refId=17315" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            内蒙古
                        </td>
                        <td>
                            <a href="http://www.nmgjsw.gov.cn" class="blue" target="_blank">内蒙古住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.nmgjsw.gov.cn/information/nmjs1/msg19995502.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            黑龙江
                        </td>
                        <td>
                            <a href="http://www.hljjs.gov.cn" class="blue" target="_blank">黑龙江建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            吉林
                        </td>
                        <td>
                            <a href="http://jst.jl.gov.cn" class="blue" target="_blank">吉林省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0431-82752590
                        </td>
                        <td>
                            吉林省长春市贵阳街287号建设大厦28楼2804房间
                        </td>
                        <td>
                            <a href="http://jst.jl.gov.cn/zwgk/xmsp/200809/t20080919_446147.html" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            辽宁
                        </td>
                        <td>
                            辽宁监理协会
                        </td>
                        <td>
                            024-22700990
                        </td>
                        <td>
                            辽宁省沈阳市和平北大街４１号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江苏
                        </td>
                        <td>
                            <a href="http://www.jscin.gov.cn" class="blue" target="_blank">江苏省住房和城乡建设厅</a>
                        </td>
                        <td>
                            025-51868916
                        </td>
                        <td>
                            江苏建设大厦2楼(南京市鼓楼区草场门大街88号)
                        </td>
                        <td>
                            <a  target="_blank" href="http://zw.jscin.gov.cn:88/lescms/websites/zw.jscin.gov.cn/doc_view.jsp?doc_id=20090617/154649421" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山东
                        </td>
                        <td>
                            <a href="http://www.sdjs.gov.cn" class="blue" target="_blank">山东省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0531-87087292<br/>0531-87087271
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            安徽
                        </td>
                        <td>
                            <a href="http://www.ahjst.gov.cn" class="blue" target="_blank">安徽省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0551-2999765
                        </td>
                        <td>
                            合肥市马鞍山路509号（马鞍山路与太湖路交叉口西北角）
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            浙江
                        </td>
                        <td>
                            <a href="http://www.zjjs.com.cn" class="blue" target="_blank">浙江省建设信息港</a>
                        </td>
                        <td>
                            0571-85213131
                        </td>
                        <td>
                            浙江省杭州市省府路8号省府大楼2号楼 
                        </td>
                        <td>
                            <a  target="_blank" href="http://www.zjjs.com.cn/DesktopModules/Winstar2004.JstZz.ExecutiveAllow/DetailInfoShow.aspx?ItemID=17bbcaa0-3782-4490-9cb1-66351d95bbd8" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            福建
                        </td>
                        <td>
                            <a href="http://www.fjjs.gov.cn" class="blue" target="_blank">福建省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0591－87617396
                        </td>
                        <td>
                            福州市北大路242号建设公寓一楼
                        </td>
                        <td>
                            <a href="http://www.fjjs.gov.cn/Htgl/Dhym/Wsbs/baznshow.aspx?FileName=bszn,sp_jl" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江西
                        </td>
                        <td>
                            <a href="http://www.jxjst.gov.cn" class="blue" target="_blank">江西省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河南
                        </td>
                        <td>
                            <a href="http://www.hnjs.gov.cn" class="blue" target="_blank">河南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0371－63820808
                        </td>
                        <td>
                            郑州市郑东新区商务内环路29号新蒲大厦14楼1406房间
                        </td>
                        <td>
                            <a href="http://www.hngcjs.net/jzj/index.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖北
                        </td>
                        <td>
                            <a href="http://www.hbzfhcxjst.gov.cn" class="blue" target="_blank">湖北省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.hbzfhcxjst.gov.cn/UpFiles/xzxk/lct/jlgcs.htm" class="blue" target="_blank">流程</a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖南
                        </td>
                        <td>
                            <a href="http://www.hunanjs.gov.cn" class="blue" target="_blank">湖南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0731-88950291
                        </td>
                        <td>
                            长沙市雨花区洞井街道和平小区湖南省住房和城乡建设厅
                        </td>
                        <td>
                            <a href="http://www.hunanjs.gov.cn/xzxk/bszn8.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广东
                        </td>
                        <td>
                            <a href="http://www.gdcic.net" class="blue" target="_blank">广东省建设信息中心</a>
                        </td>
                        <td>
                            020－83754271
                        </td>
                        <td>
                            广州市华乐路53号华乐大厦南塔14层（花园酒店东侧）
                        </td>
                        <td>
                            <a href="http://www.gdzczx.com/gdzczxIms/zcdt/" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广西
                        </td>
                        <td>
                            <a href="http://www.gxcic.net" class="blue" target="_blank">广西建设厅</a>
                        </td>
                        <td>
                            0771-5595842
                        </td>
                        <td>
                            广西南宁市怡宾路6号
                        </td>
                        <td>
                            <a href="http://www.gxcic.net/twgk/Show.aspx?id=45238" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            海南
                        </td>
                        <td>
                            <a href="http://www.hncic.net" class="blue" target="_blank">海南省住房和城乡建设厅建筑管理处</a>
                        </td>
                        <td>
                             0898-66217166
                        </td>
                        <td>
                            海口市文明中路文联路6号金泰大酒店2楼（原晶宇大酒店）
                        </td>
                        <td>
                            <a href="http://www.hizw.gov.cn/hiSP/html/WorkFlow/?1450_1" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            云南
                        </td>
                        <td>
                            <a href="http://www.ynjst.gov.cn" class="blue" target="_blank">云南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0871-4163856
                        </td>
                        <td>
                            云南省昆明市滇池路红塔路口昆明二建大厦三楼云南注册建造师管理办公室
                        </td>
                        <td>
                            <a href="http://www.ynjst-jgc.com/skynet/jgcweb/TypeInfo.aspx?id=2128" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            贵州
                        </td>
                        <td>
                            <a href="http://www.gzjs.gov.cn" class="blue" target="_blank">贵州省住房和城乡建设厅</a>
                        </td>
                        <td>
                             0851-5360016<br/>0851-5360380
                        </td>
                        <td>
                            延安西路２号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            四川
                        </td>
                        <td>
                            <a href="http://web.scjst.gov.cn" class="blue" target="_blank">四川监理协会</a>
                        </td>
                        <td>
                            028-85080802
                        </td>
                        <td>
                            四川省成都市武侯区高升桥南街11号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            西藏
                        </td>
                        <td>
                            <a href="http://www.xzcs.gov.cn" class="blue" target="_blank">西藏自治区建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            陕西
                        </td>
                        <td>
                            <a href="http://www.shaanxijs.gov.cn" class="blue" target="_blank">陕西省建设厅</a>
                        </td>
                        <td>
                            029-87283010
                        </td>
                        <td>
                            陕西省西安市南新街28号德邻酒店3楼 
                        </td>
                        <td>
                            <a href="http://www.sjzz.org.cn/zhiye/721.shtml" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            甘肃
                        </td>
                        <td>
                            <a href="http://www.gsjs.com.cn" class="blue" target="_blank">甘肃省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            宁夏
                        </td>
                        <td>
                            <a href="http://www.nxzczx.com/SiteAcl.srv?id=2288188&publicstr=str" class="blue" target="_blank">宁夏回族自治区住房和城乡建设厅</a>
                        </td>
                        <td>
                            0951-5179098
                        </td>
                        <td>
                            银川市兴庆区上海东路48号(建设大厦八楼注册科)
                        </td>
                        <td>
                            <a href="http://www.nxzczx.com/SiteAcl.srv?id=2288286&aid=2010003202&channelid=2288208" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            新疆
                        </td>
                        <td>
                            <a href="http://www.xjjs.gov.cn" class="blue" target="_blank">新疆建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.xjjs.gov.cn/main/NewsList.aspx?catId=3310" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            青海
                        </td>
                        <td>
                            <a href="http://www.qhcin.gov.cn" class="blue" target="_blank">青海省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0971-6146535
                        </td>
                        <td>
                            西宁市五四大街4号（建筑科技书店三楼）
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                </table>
            </div>
            <div id="kc_book"class="bc pt">
                 <p class="gn">勘察设计师执业资格注册管理机构通讯录</p>
                   <table class="tb_c tl">
                    <tr>
                        <td class="gray procv">
                            省(市)
                        </td>
                        <td class="gray orgination">
                            注册管理机构
                        </td>
                        <td class="gray phnuber">
                            联系电话
                        </td>
                         <td class=" gray addr">
                            办理地址
                        </td>
                         <td class="gray material">
                            材料
                        </td>
                         <td class="gray prgs">
                            流程
                        </td>
                    </tr>
                    <tr>
                        <td>
                            全国
                        </td>
                        <td>
                            全国勘察设计注册工程师电气专业管理委员会
                        </td>
                        <td>
                            010-58388763
                        </td>
                        <td>
                            北京市西城区安德路65号
                        </td>
                        <td>
                           -
                        </td>
                        <td>
                           -
                        </td>
                    </tr>
                      <tr>
                        <td>
                            北京
                        </td>
                        <td>
                            <a href="http://www.bjjs.gov.cn" class="blue" target="_blank">北京规划委员会（勘测办）</a>
                        </td>
                        <td>
                            010-68057264<br/>010-88073196
                        </td>
                        <td>
                            北京市西城区南礼士路60号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                      <tr>
                        <td>
                            天津
                        </td>
                        <td>
                            <a href="http://www.tjcac.gov.cn" class="blue" target="_blank">天津市勘察设计管理处</a>
                        </td>
                        <td>
                            020-27129814
                        </td>
                        <td>
                            天津市和平区南京路131号城建大厦A座2004
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            上海
                        </td>
                        <td>
                            <a href="http://www.ciac.sh.cn" class="blue" target="_blank">上海建筑建材业网</a>
                        </td>
                        <td>
                            021-27129778
                        </td>
                        <td>
                            上海市徐汇区小木桥路683号受理大厅
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            重庆
                        </td>
                        <td>
                            <a href="http://www.ccc.gov.cn" class="blue" target="_blank">重庆市城乡建委勘察设计处</a>
                        </td>
                        <td>
                            023-63672112
                        </td>
                        <td>
                            渝中区长江一路58号市城乡建委政务服务中心4楼12号窗口
                        </td>
                        <td>
                            <a href="http://www.ccc.gov.cn/bsdt/bszn/2011-04-02-186847.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河北
                        </td>
                        <td>
                            <a href="http://www.hebjs.gov.cn " class="blue" target="_blank">河北省住房和城乡建设厅执业资格注册中心</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山西
                        </td>
                        <td>
                            <a href="http://www.sxjs.gov.cn" class="blue" target="_blank">山西省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0351-3581377
                        </td>
                        <td>
                            山西省太原市建设北路85号山西省住房和城乡建设厅政务大厅
                        </td>
                        <td>
                            <a href="http://www.sxjs.gov.cn/NewsRead.aspx?CatalogId=142&refId=17318" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            内蒙古
                        </td>
                        <td>
                            <a href="http://www.nmgjsw.gov.cn" class="blue" target="_blank">内蒙古住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.nmgjsw.gov.cn/information/nmjs1/msg19995480.html" class="blue" target="_blank">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            黑龙江
                        </td>
                        <td>
                            <a href="http://www.hljjs.gov.cn" class="blue"  target="_blank">黑龙江建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            吉林
                        </td>
                        <td>
                            <a href="http://jst.jl.gov.cn" class="blue" target="_blank">吉林省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0431-82752400
                        </td>
                        <td>
                            吉林省长春市贵阳街287号建设大厦28楼2803房间
                        </td>
                        <td>
                            <a href="http://jst.jl.gov.cn/zwgk/xmsp/200809/t20080919_446145.html" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            辽宁
                        </td>
                        <td>
                            辽宁省住房和城乡建设执业资格注册中心
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.zczx.lnjst.gov.cn/(S(ajl42n55mifzpi45q2kilt45))/zyzc/childzhu.aspx" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江苏
                        </td>
                        <td>
                            <a href="http://www.jscin.gov.cn" class="blue" target="_blank">江苏省住房和城乡建设厅</a>
                        </td>
                        <td>
                            025-51868918<br/>025-51868218
                        </td>
                        <td>
                            江苏建设大厦2楼(南京市鼓楼区草场门大街88号)
                        </td>
                        <td>
                            <a href="http://zw.jscin.gov.cn:88/lescms/websites/zw.jscin.gov.cn/doc_view.jsp?doc_id=20090617/154609828" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            山东
                        </td>
                        <td>
                            <a href="http://www.sdjs.gov.cn" class="blue" target="_blank">山东省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0531-87087287<br/>0531-87087271
                        </td>
                        <td>
                            - 
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            安徽
                        </td>
                        <td>
                            <a href="http://www.ahjst.gov.cn" class="blue" target="_blank">安徽省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0551-2999765
                        </td>
                        <td>
                            合肥市马鞍山路509号（马鞍山路与太湖路交叉口西北角）
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            浙江
                        </td>
                        <td>
                            <a href="http://www.zjjs.com.cn" class="blue" target="_blank">浙江省建设信息港</a>
                        </td>
                        <td>
                            0571-85216767
                        </td>
                        <td>
                            浙江省杭州市省府路8号省府大楼2号楼 
                        </td>
                        <td>
                            <a  target="_blank" href="http://www.zjjs.com.cn/DesktopModules/Winstar2004.JstZz.ExecutiveAllow/DetailInfoShow.aspx?ItemID=c698ab74-d725-4b95-948f-3d0c65d3d936" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            福建
                        </td>
                        <td>
                            <a href="http://www.fjjs.gov.cn" target="_blank" class="blue">福建省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0591－87617396
                        </td>
                        <td>
                            福州市北大路242号建设公寓一楼
                        </td>
                        <td>
                            <a href="http://www.fjjs.gov.cn/Htgl/Dhym/Wsbs/baznshow.aspx?FileName=bszn,sp_kc" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            江西
                        </td>
                        <td>
                            <a href="http://www.jxjst.gov.cn" class="blue" target="_blank">江西省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            河南
                        </td>
                        <td>
                            <a href="http://www.hnjs.gov.cn" class="blue" target="_blank">河南省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖北
                        </td>
                        <td>
                            <a href="http://www.hbzfhcxjst.gov.cn" class="blue" target="_blank">湖北省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            湖南
                        </td>
                        <td>
                            <a href="http://www.hunanjs.gov.cn" class="blue" target="_blank">湖南省建设厅勘察设计处</a>
                        </td>
                        <td>
                            0731-4455751<br/>0731-88950310
                        </td>
                        <td>
                            湖南省长沙市洞井街道和平社
                        </td>
                        <td>
                            <a href="http://www.hunanjs.gov.cn/xzxk/bszn5.html" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广东
                        </td>
                        <td>
                            <a href="http://www.gdcic.net" target="_blank" class="blue">广东住房和城乡建设厅行政许可管理处</a>
                        </td>
                        <td>
                            020－83754622
                        </td>
                        <td>
                            广东省广州市越秀区华乐路53号华乐大厦南塔14楼
                        </td>
                        <td>
                            <a href="http://www.gdzczx.com/gdzczxIms/zcdt/" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            广西
                        </td>
                        <td>
                            <a href="http://www.gxcic.net" class="blue" target="_blank">广西建设厅</a>
                        </td>
                        <td>
                            0771-5595534
                        </td>
                        <td>
                            广西南宁市怡宾路6号
                        </td>
                        <td>
                            <a href="http://www.gxcic.net/twgk/Show.aspx?id=45244" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            海南
                        </td>
                        <td>
                            <a href="http://www.hncic.net" class="blue" target="_blank">海南省住房和城乡建设厅建筑管理处</a>
                        </td>
                        <td>
                             0898-66219099<br/>0898-65343591
                        </td>
                        <td>
                            海口市海府路59号厅办公楼二楼204房
                        </td>
                        <td>
                            <a href="http://www.hizw.gov.cn/hiSP/html/WorkFlow/?1466_1" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            云南
                        </td>
                        <td>
                            <a href="http://www.ynjst.gov.cn" class="blue" target="_blank">云南省住房和城乡建设厅勘察设计处</a>
                        </td>
                        <td>
                            0871-4618387<br/>0871-4320546
                        </td>
                        <td>
                            云南省昆明市红塔东路3号
                        </td>
                        <td>
                            <a href="http://www.ynjst.gov.cn:84/kcsj/_info.do?method=view&id=241"  target="_blank"class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            贵州
                        </td>
                        <td>
                            <a href="http://www.gzjs.gov.cn" class="blue" target="_blank">贵州省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0851-5360130<br/>0851-5360016
                        </td>
                        <td>
                            延安西路２号
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            四川
                        </td>
                        <td>
                            <a href="http://web.scjst.gov.cn" class="blue" target="_blank">四川省住房和城乡建设厅</a>
                        </td>
                        <td>
                            028-85533312<br/>028-85568202
                        </td>
                        <td>
                            四川省成都市成都市人民南路四段36号621
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                    <tr>
                        <td>
                            西藏
                        </td>
                        <td>
                            <a href="http://www.xzcs.gov.cn" class="blue" target="_blank">西藏自治区建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            陕西
                        </td>
                        <td>
                            <a href="http://www.shaanxijs.gov.cn" class="blue" target="_blank">陕西省建设厅</a>
                        </td>
                        <td>
                            029-87283010 
                        </td>
                        <td>
                            陕西省西安市南新街28号德邻酒店311
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            甘肃
                        </td>
                        <td>
                            <a href="http://www.gsjs.com.cn" class="blue" target="_blank">甘肃省住房和城乡建设厅</a>
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            宁夏
                        </td>
                        <td>
                            <a href="http://www.nxzczx.com/SiteAcl.srv?id=2288188&publicstr=str" target="_blank" class="blue">宁夏回族自治区住房和城乡建设厅</a>
                        </td>
                        <td>
                            0951-5179098
                        </td>
                        <td>
                            银川市兴庆区上海东路48号(建设大厦八楼注册科)
                        </td>
                        <td>
                            <a href="http://www.nxzczx.com/SiteAcl.srv?id=2288286&aid=2010003211&channelid=2288208" target="_blank" class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            新疆
                        </td>
                        <td>
                            新疆建设厅
                        </td>
                        <td>
                            0951-5179098<br/>0991-2830155
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            <a href="http://www.xjjs.gov.cn/main/NewsDetail.aspx?Id=38431"  target="_blank"class="blue">材料</a>
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                        <td>
                            青海
                        </td>
                        <td>
                            <a href="http://www.qhcin.gov.cn" class="blue" target="_blank">青海省住房和城乡建设厅</a>
                        </td>
                        <td>
                            0971-6146535
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                        <td>
                            -
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <!-- layout::Public:footersimple::60 -->
        <!-- layout::Public:comtool::60 -->
    </body>
</html>
